### ISSUE TITLE
飲みたいお酒一覧（希望込）

### ISSUE THREAD

**Issue by MizuTakeuchi** [MizuTakeuchi/Sake#3]
## WHY
美味しいお酒が飲みたい

## WHAT
下記を記載
- 推薦者の名前: 
- 酒造名: 
- 品名: 
- 概算価格: 
- URL: 
- MEMO: 

手に入るかどうかはわからないものも含む

**Comment by MizuTakeuchi** [comment]
## たんじさんレコメンド
上川大雪酒造　
純米大吟醸
700ml 3630円
http://shop.kamikawa-taisetsu.co.jp/html/page22.html

**Comment by tan-z-tan** [comment]
- @tan-z-tan
- 会津酒造
- 山の井
- 1800 JPY / 720ml
- URL https://www.syusendo-horiichi.co.jp/SHOP/11860.html

**Comment by MizuTakeuchi** [comment]
- 推薦者の名前:  mizuki takeuchi
- 酒造名: 高木酒造（高知県）
- 品名:  Ailien
- 概算価格:  四合瓶で1,850 (税別)、一升で3700円
- URL: https://kurand.jp/products/aliens
- MEMO: 淡麗辛口
くらんどで飲んで美味しかった
